### ISSUE TITLE
Most webpages do not handle resizing of the viewport well

### ISSUE THREAD

**Issue by ghost** [nathangeater/coms319#10]
Most of the webpages have undefined behaviour when the viewport is resized. It happens for both vertical and horizontal resizing. For example, when the viewport's vertical height is changed to be much smaller than normal, the footer will not be in the correct place and most text will be displayed over the footer.

**Comment by 7079192991** [comment]
you can use fluid layout for your footer 
means instead of the size taken in pixel you can use size in percentage .
